-- ============================================================
-- The Watchman — Initial schema
-- ============================================================
-- Run order: 00001 → 00002 → 00003 → 00004 → 00005
-- Apply via Supabase Studio SQL editor or `supabase db push`.
-- ============================================================

create extension if not exists "pgcrypto";

-- ---------- enums ----------
do $$ begin
  create type user_role as enum ('super_admin', 'admin', 'member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type user_status as enum ('pending', 'approved', 'rejected');
exception when duplicate_object then null; end $$;

do $$ begin
  create type event_status as enum ('draft', 'published', 'cancelled', 'completed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type rsvp_status as enum ('going', 'maybe', 'not_going');
exception when duplicate_object then null; end $$;

do $$ begin
  create type chat_type as enum ('main', 'event');
exception when duplicate_object then null; end $$;

do $$ begin
  create type media_type as enum ('none', 'image', 'video');
exception when duplicate_object then null; end $$;

-- ---------- profiles ----------
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique not null references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text,
  profile_photo_url text,
  bio text,
  occupation text,
  company text,
  instagram_url text,
  interests text[] default '{}'::text[],
  role user_role not null default 'member',
  status user_status not null default 'pending',
  points_total integer not null default 0,
  invited_by_user_id uuid references public.profiles(id) on delete set null,
  invite_code text unique not null default lower(replace(gen_random_uuid()::text, '-', '')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_active_at timestamptz
);

create index if not exists profiles_status_idx on public.profiles(status);
create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_invited_by_idx on public.profiles(invited_by_user_id);
create index if not exists profiles_points_idx on public.profiles(points_total desc);

-- ---------- invites (single-use codes generated by members) ----------
-- profiles.invite_code is each member's permanent personal link.
-- This table is for any future use of one-time codes; for MVP we read invite_code from profiles.
create table if not exists public.invites (
  id uuid primary key default gen_random_uuid(),
  invite_code text unique not null,
  created_by_user_id uuid not null references public.profiles(id) on delete cascade,
  used_by_user_id uuid references public.profiles(id) on delete set null,
  status text not null default 'active', -- active | used | revoked
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create index if not exists invites_created_by_idx on public.invites(created_by_user_id);

-- ---------- events ----------
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  event_date date not null,
  start_time time,
  end_time time,
  location_name text,
  address text,
  latitude double precision,
  longitude double precision,
  image_url text,
  created_by_user_id uuid not null references public.profiles(id) on delete restrict,
  status event_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists events_date_idx on public.events(event_date);
create index if not exists events_status_idx on public.events(status);

-- ---------- event rsvps ----------
create table if not exists public.event_rsvps (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status rsvp_status not null default 'going',
  checked_in boolean not null default false,
  checked_in_at timestamptz,
  checkin_latitude double precision,
  checkin_longitude double precision,
  created_at timestamptz not null default now(),
  unique (event_id, user_id)
);

create index if not exists rsvps_event_idx on public.event_rsvps(event_id);
create index if not exists rsvps_user_idx on public.event_rsvps(user_id);

-- ---------- chats ----------
create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  type chat_type not null,
  event_id uuid references public.events(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists chats_main_singleton_idx
  on public.chats((true)) where type = 'main';
create unique index if not exists chats_event_unique_idx
  on public.chats(event_id) where type = 'event';

-- ---------- messages ----------
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text,
  media_url text,
  media_type media_type not null default 'none',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists messages_chat_created_idx on public.messages(chat_id, created_at desc);
create index if not exists messages_user_idx on public.messages(user_id);

-- ---------- message reactions ----------
create table if not exists public.message_reactions (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction_type text not null default 'like',
  created_at timestamptz not null default now(),
  unique (message_id, user_id, reaction_type)
);

create index if not exists reactions_message_idx on public.message_reactions(message_id);

-- ---------- polls ----------
create table if not exists public.polls (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid references public.chats(id) on delete cascade,
  event_id uuid references public.events(id) on delete cascade,
  question text not null,
  created_by_user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  closes_at timestamptz
);

create table if not exists public.poll_options (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.polls(id) on delete cascade,
  option_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.poll_votes (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.polls(id) on delete cascade,
  poll_option_id uuid not null references public.poll_options(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (poll_id, user_id)
);

create index if not exists poll_votes_poll_idx on public.poll_votes(poll_id);

-- ---------- points ledger ----------
create table if not exists public.points_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  action_type text not null,
  points integer not null,
  related_entity_type text,
  related_entity_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists points_ledger_user_idx on public.points_ledger(user_id, created_at desc);
create index if not exists points_ledger_action_idx on public.points_ledger(action_type);

-- ---------- notifications ----------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  read boolean not null default false,
  related_entity_type text,
  related_entity_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx on public.notifications(user_id, created_at desc);
create index if not exists notifications_unread_idx on public.notifications(user_id) where read = false;

-- ---------- shops (placeholder) ----------
create table if not exists public.shops (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  shopify_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- ensure single main chat exists ----------
insert into public.chats (type, title)
select 'main', 'Main Room'
where not exists (select 1 from public.chats where type = 'main');
